// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB84rYZyw74GlASmY6uyIziYLKbctpJ9JE',
    appId: '1:1001385583616:web:36224b11dfd7514b22e4e5',
    messagingSenderId: '1001385583616',
    projectId: 'flutterapp-7dd66',
    authDomain: 'flutterapp-7dd66.firebaseapp.com',
    databaseURL: 'https://flutterapp-7dd66-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutterapp-7dd66.appspot.com',
    measurementId: 'G-48W8SKEWR1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_emlZPnVIGlwDnsjrxODHbTaoRGshfJI',
    appId: '1:1001385583616:android:abe498be80b64a2522e4e5',
    messagingSenderId: '1001385583616',
    projectId: 'flutterapp-7dd66',
    databaseURL: 'https://flutterapp-7dd66-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutterapp-7dd66.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFQA0OlkQFjVca6UTbQl7Yl2W633UAuEI',
    appId: '1:1001385583616:ios:7543a8a0b285147722e4e5',
    messagingSenderId: '1001385583616',
    projectId: 'flutterapp-7dd66',
    databaseURL: 'https://flutterapp-7dd66-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutterapp-7dd66.appspot.com',
    iosClientId: '1001385583616-c1kgrja30es9sutqpggfrltkspvndn9p.apps.googleusercontent.com',
    iosBundleId: 'com.example.dropshop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFQA0OlkQFjVca6UTbQl7Yl2W633UAuEI',
    appId: '1:1001385583616:ios:7543a8a0b285147722e4e5',
    messagingSenderId: '1001385583616',
    projectId: 'flutterapp-7dd66',
    databaseURL: 'https://flutterapp-7dd66-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutterapp-7dd66.appspot.com',
    iosClientId: '1001385583616-c1kgrja30es9sutqpggfrltkspvndn9p.apps.googleusercontent.com',
    iosBundleId: 'com.example.dropshop',
  );
}
